name: Auto Update Data

on:
  schedule:
    - cron: '0 * * * *' # Har 1 ghante mein apne aap chalega
  workflow_dispatch: # Isse aap button daba kar bhi chala sakte hain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install libraries
        run: pip install requests

      - name: Run script
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json
          git commit -m "Auto update data" || exit 0
          git push
